routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@showLoginPage');
Route::post('/check', 'Auth\RegisterController@checkRegistred');
Route::post('/register', 'Auth\RegisterController@register')->name('inscription');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/privacy-policy', 'HomeController@policy');

Route::get('/accueil', 'HomeController@index')->name('home');
Route::get('/classement', 'GameController@ranking')->name('ranking');

Route::post('/start-game', 'GameController@startGame');
Route::post('/end-game', 'GameController@endGame');




Route::get('admin/login', 'Auth\LoginController@showAdminLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\LoginController@adminLogin');
Route::get('admin/logout', 'Auth\LoginController@logout')->name('logout2');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::get('/users', 'AdminController@users')->name('users');
    Route::post('/moderation', 'AdminController@moderation')->name('moderation');
	Route::get('/exportExcel','AdminController@exportExcel')->name('export');
});

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\UserExports;
use App\Http\Controllers\Controller;
use App\Models\Game;
use App\Models\Photo;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {


        $usersCount = User::all()->count();
        $gameCount = Game::all()->count();

        $users = User::with('games')->withCount('games')->get();
        return view('admin.home')->with([
			'users'					=>$users,
            'usersCount'            =>$usersCount,
            'gameCount'            	=>$gameCount
        ]);
    }


	/**
	 * Export to excel
	 */
	public function exportExcel()
	{
		return Excel::download(new UserExports, 'jellinowin-user-list.xlsx');
	}
}

resources/views/admin/home.blade.php
@extends('admin.layouts.app')

@section('content')

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <a href="{{ route('admin.export') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <div class="row justify-content-center">

        <!-- Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Users</div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{$usersCount}}</div>
                                </div>
                                <div class="col">
                                   Utilisateurs
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Nombre</div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{$gameCount}}</div>
                                </div>
                                <div class="col">
                                    Jeux
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-gamepad fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>


    <div class="row justify-content-center">

        <ul class="list-group w-100">

            @foreach($users as $user)
                <li class="list-group-item d-flex align-items-center">
                    <div class="mr-3">
                        <img src="http://graph.facebook.com/{{ $user->fb_id }}/picture?type=square" class="rounded-circle" alt="">
                    </div>
                    <div class="mr-3">
                        <h5 class="text-primary mb-1">{{ $user->name }} <small>ID : {{ $user->fb_id }}</small></h5>
                        {{ $user->email }} - {{ $user->phone }}  - Total games :{{ $user->games_count }} - <small class="text-muted"> <i class="fas fa-clock"></i> {{ $user->timeSpent() }}</small>
                    </div>
                    <div class="ml-auto text-primary text-right">
                        <h5 class="mb-0">
                            <i class="fas fa-star"></i> {{ $user->maxScore() }}

                        </h5>

                    </div>



                </li>
            @endforeach
        </ul>


    </div>


@endsection

resources/views/admin/users.blade.php
@extends('admin.layouts.app')

@section('content')

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Utilisateur</h1>
{{--        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>--}}
    </div>

    <div class="row justify-content-center">

        <div class="card w-100">
                @foreach($players as $player)
                    <li class="list-group-item p-4">
                        <div class="row align-items-center">
                            <div class="col">
                                <div class="row align-items-center">
                                    <div class="col-md-7 d-flex">
                                <span>
                                    <img src="{{ Avatar::create($player->name)->toBase64() }}" width="30px" class=" border rounded-pill border-white float-left" />
                                </span>
                                        <div class="d-inline-block float-left col">
                                            <h5 class="d-block m-0">{{ $player->name }}</h5>
                                            <i class="fas fa-envelope"></i> <small class="">{{ $player->email }} |  <i class="fas fa-calendar"></i> {{ $player->created_at  }}</small>
                                        </div>
                                    </div>

                                </div>
                            </div>

                        </div>

                    </li>
                @endforeach
        </div>

    </div>


@endsection